### ISSUE TITLE
ViReMa memory error in large datasets that align poorly

### ISSUE THREAD

**Issue by jrkirk61** [BROOKELAB/Influenza-virus-DI-identification-pipeline#1]
For larger input datasets (1.8 - 2.6Gb of reads), I have been receiving the following error that is independent of Nextflow. In particular, I have given sample 36B (2.6Gb) huge amounts of memory (anywhere from 200-300Gb), and this error is returned before it finishs. I've been told that this sample can be ignored for the time-being, however, it is very strange that ViReMa needs so much memory to finish, especially in datasets that don't align well to the reference. Smaller datasets than this, have required anywhere from 30 - 160Gb of memory, so it varies quite a bit. 

```
Traceback (most recent call last):
    File "/home/groups/hpcbio_shared/cbrooke_lab/apps/ViReMa_0.6/ViReMa.py", line 538, in <module>
      IterateAlignments(cfgvars.File1)
    File "/home/groups/hpcbio_shared/cbrooke_lab/apps/ViReMa_0.6/ViReMa.py", line 457, in IterateAlignments
      Alignment('TEMPREADS', '-q', cfgvars.Seed)
    File "/home/groups/hpcbio_shared/cbrooke_lab/apps/ViReMa_0.6/ViReMa.py", line 342, in Alignment
      call(['bowtie', ReadType, '-n', str(cfgvars.Mismatches), '-l', str(Seed), '-e', '100000', '--quiet', '--mm', '-p', cfgvars.Threads, '--best', '-S', '--sam-nohead', cfgvars.Lib1, ReadsIn, 'TEMPSAM1'])
    File "/home/apps/software/Python/2.7.13-IGB-gcc-4.9.4/lib/python2.7/subprocess.py", line 168, in call
      return Popen(*popenargs, **kwargs).wait()
    File "/home/apps/software/Python/2.7.13-IGB-gcc-4.9.4/lib/python2.7/subprocess.py", line 390, in __init__
      errread, errwrite)
    File "/home/apps/software/Python/2.7.13-IGB-gcc-4.9.4/lib/python2.7/subprocess.py", line 916, in _execute_child
      self.pid = os.fork()
  OSError: [Errno 12] Cannot allocate memory
```

**Comment by LohmannJens** [comment]
Actually, I am having a similar problem right now.
